### ISSUE TITLE
Add Flux 1 dev and Flux ControlNets

### ISSUE THREAD

**Issue by clemenslindner** [daxcay/ComfyUI-Nexus#3]
Hi @daxcay , 

would it be possible to add Flux as well as flux controllers to your collab setup. 

Thank you very much!

**Comment by jerrydavos** [comment]
Hey, in your Host machine, you can add flux models as well as it's controlnets, and use as you would normally use. 

If your Host Machine has enough vram and can support Flux and it's models then it can run anywhere you use the client's multiplayer comfyui. 

Nexus custom nodes only adds the "multiplayer" support, the working is same as usual Comfyui.

If you face any bugs related to nexus's multiplayer feature not being able to run flux or so, you can report it here.
