### ISSUE TITLE
some workflows not showing

### ISSUE THREAD

**Issue by BenDes21** [daxcay/ComfyUI-Nexus#5]
Hello there, when Im trying to load some of my workflows ( as admin ), nothing show, the workflow is completely empty compare to the others. Any solutions? ( I refreshed, deleted the " empty workflow " and reload the .json but it's still not showing )

Thanks

**Comment by daxcay** [comment]
Update to the latest version of comfy.

After logging in as admin, then only you will see the comfy menu in the bottom right, 
Now from there clear and reset the workflow and drag a new workflow json file.

If there is no error in workflow it will load. and you could see it. (try to reset view in case it looks empty)
Now when another user joins he/she only see the new workflow after backup is being made that is after 60 seconds of you becoming an admin.

To see the backup press `lalt+o`. if its there everything is working fine.

Now if there is error feel free to contact me on discord: https://discord.gg/Z44Zjpurjp
